# This is a basic workflow that is manually triggered

name: 01b-hola-sergio

on:
  push:
    branches:
      - 'main'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  hola-Sergio-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: imprime Sergio
      run: echo "Hello Sergio"
